### ISSUE TITLE
2.0 Version, Username and password problem

### ISSUE THREAD

**Issue by pablo-MA** [cytomine/Cytomine-bootstrap#17]
What is the username and password for the admin after installation on Linux?

**Comment by geektortoise** [comment]
Hello, 

You can find the (first) password of the admin user in the cytomineconfig.groovy configuration file.

or you can run the command
cat configs/core/cytomineconfig.groovy | grep adminPassword

We recommand you to change it at your first connexion.

**Comment by pablo-MA** [comment]
Hello I tried with the random generated password but I had no success. I obiously used "admin" as username. Do you have any idea what could be the problem? 
![screenshot](https://user-images.githubusercontent.com/57932567/69594781-07ac6780-0fc3-11ea-97a7-c646f7acef6c.png)

**Comment by geektortoise** [comment]
Hello, 

The adminPassword doesn't override the old one if the database has already been set. So if there was an start_deploy run then a rerun of the init.sh, the initiation script will change the adminPassword but doesn't override the one into the Cytomine database.

It it is the case, run the following scripts 

sudo sh clean_docker_keep_data.sh
sudo docker volume rm postgis_data #clean the database
sudo sh restart.sh

and retry to connect with "admin" and the password into the configs/core/cytomineconfig.groovy file

**Comment by mizjaggy18** [comment]
Hi, Can I request to reopen this? I just installed Cytomine in my Ubuntu 18.04 machine, but I did the 'init.sh' and 'start.sh' twice because I mistakenly create data paths directories inside /home.  

I've tried `sudo sh clean_docker_keep_data.sh`

And it returned `sh: 0: Can't open clean_docker_keep_data.sh`

For `sudo docker volume rm postgis_data #clean the database`

It returned `Error: No such volume: postgis_data`

I'm stuck at this for hours. I've tried 'clean_config.sh', delete all the containers in docker and rerun the 'init.sh' and 'start.sh' but it still returned 'Bad login or password'.

I really appreciate your kind assistance. Thank you.
