### ISSUE TITLE
software_router uses 100% of CPU

### ISSUE THREAD

**Issue by anttikos** [cytomine/Cytomine-bootstrap#29]
On some VMs, the software_router container seems to take 100% of CPU, even though no-one is accessing Cytomine at the time. The CPU usage stays 100% constantly, and restarting Cytomine / VM doesn't seem to help. However, this is not happening on all the VMs... we have 4 similar VMs, each of them have Cytomine set up with the same scripts and with identical configuration.

When I ran top-command inside software_router container, I'm getting the following output:
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  140 root      20   0  563772  34056  14560 S 98.5  0.2 117:45.53 dockerd
```

I'm not sure how to debug further, any ideas?

**Comment by geektortoise** [comment]
Hello, 

As you have a dockerd process running inside the software_router container, I'm wondering what is your version of Cytomine.

Since the V3, we have fully modified the external softwares architecture.

Do you know which version of Cytomine you are using ?
Inside the software_router container what are the running process ?
(a simple `ps aux` is enough at this time)

**Comment by anttikos** [comment]
Thank you for your reply and help!

Sorry, I posted this issue too hastily, as I also later realized that this might be already fixed in V3. 

We are using 2.1.x version, and the plan is to upgrade to v3 soonish, so we probably won't have time to dig deeper into this. The issue can be closed if you don't think it's relevant with v3, and I can re-open or re-post the issue, if it's also happening with v3.

**Comment by geektortoise** [comment]
I will close it for now. We can re-open if relevant with the V3.

Have a nice day!
